config/routes.rb
SampleApp::Application.routes.draw do
  resources :images

  # resources :users do
  #   member do
  #     get :following, :followers
  #   end
  # end
  # resources :sessions,      only: [:new, :create, :destroy]
  # resources :microposts,    only: [:create, :destroy]
  # resources :relationships, only: [:create, :destroy]

  resources :image
  root to: 'images#new'
  # root to: 'static_pages#home'
  # match '/signup',  to: 'users#new',            via: 'get'
  # match '/signin',  to: 'sessions#new',         via: 'get'
  # match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/image.rb
class Image < ActiveRecord::Base
  dragonfly_accessor :image

  attr_accessible :image, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
      @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = "image analysed!"
      redirect_to image_path @image
    else
      render 'new'
    end
  end

  def show
    @image = Image.find(params[:id])
    file_url = Rails.root.to_s + "/public/" + @image.image.remote_url
    @exif = EXIFR::JPEG::new(file_url)
    query = dps_to_dd(@exif.gps_latitude || 0, @exif.gps_latitude_ref|| 0, @exif.gps_longitude|| 0, @exif.gps_longitude_ref|| 0)
    @address = Geocoder.search(query).first
  end

  private

    def image_params
      params.require(:image).permit(:image, :title)
    end

  def dps_to_dd(latitude,ref_latitude,longitude, ref_longitude)
    if ref_longitude.eql?"W"
      longitude[0]=-longitude[0]
      longitude[1]=-longitude[1]
      longitude[2]=-longitude[2]
    end
    if ref_longitude.eql?"S"
      latitude[0]=-latitude[0]
      latitude[1]=-latitude[1]
      latitude[2]=-latitude[2]
    end
    dd1 = (latitude[0] + latitude[1]/60 + latitude[2]/3600).to_f
    dd2 = (longitude[0] + longitude[1]/60 + longitude[2]/3600).to_f
    return [dd1, dd2]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	helper_method :dps_to_dd
  def home
		
  end

  def dps_to_dd(latitude,ref_latitude,longitude, ref_longitude)
  	
      longitude = longitude.map{ |long| -long }  if ref_longitude.eql?"W"
      latitude = latitude.map{ |lat| -lat }  if ref_longitude.eql?"S"
      
      dd1 = (latitude[0] + latitude[1]/60 + latitude[2]/3600).to_f
      dd2 = (longitude[0] + longitude[1]/60 + longitude[2]/3600).to_f
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/index.html.erb
<h3>Your image list</h3>

<% @images.each_with_index do |img, index| %>
  <div class="row">
		<aside class="span3">
			<li>
  	 		<%= link_to image_tag(img.image.thumb('180x180#').url, 
				alt: img.title, class: 'img-thumbnail'),
        img.image.url , target: '_blank' %>

				<a class="btn btn-large btn-info" href="images/<%= index+1 %>">Exif informations</a>
				<br>
				<br>
				<br>
			</li>
		</aside>
		<aside class="span9">
			<h5>Title </h5><%= (img.image.name) %><br><br>
			<h5>Size </h5><%= (img.image.size/1024).round(2 )%> Ko<br>
		</aside>
	</div>
<% end %>

<button class="btn btn-large btn-primary" onclick="openDialog();">
     <i class="icon-download-alt icon-white"></i> Download metadatas into CSV file</button>

app/views/images/new.html.erb
  <div id="dropper" class="center hero-unit">
    <h1>Extract data from pictures</h1>
    <h2>Open a picture or drop it here.</h2>

<button class="btn btn-large btn-primary" id="openPicture" style="display:show" onclick="openDialog();">
     <i class="icon-search icon-white"></i> Open picture</button>
<br>
<%= simple_form_for @image do |img| %>

  <%= img.file_field :image, required: true, accept: 'image/png,image/jpeg', hint: 'In order to analyse the exif data and change them please submit the corresponding image', class: "btn btn-primary", id:"dialog", style:"display:none" %>

 <%= button_tag(type: 'submit', class: "btn-large btn-success", style:"display:none", id:"createPicture") do %>
    <i class="icon-plus-sign icon-white"></i> Create picture
  <% end %>

<% end %>

<img id="currentImage" style="display:none" IMG HEIGHT=180 WIDTH=180 src="#" />

<h4><font color="grey">Learn more about
    <a href="https://en.wikipedia.org/wiki/Exchangeable_image_file_format">EXIF files</a>.
    </font>
</h4>
</div>

<script type="text/javascript">
	function readURL(input) {
		if (input.files && input.files[0]) {
		    var reader = new FileReader();
		    reader.onload = function (e) {
		        $('#currentImage').attr('src', e.target.result);
		    }
		    reader.readAsDataURL(input.files[0]);
		}
	}

	$("#dialog").change(function(){
		readURL(this);
       	 	document.getElementById('createPicture').style = "display:show";
        	document.getElementById('currentImage').style = "display:show";
	});
    function openDialog(){
        document.getElementById('dialog').click();
    }
</script>

app/views/images/show.html.erb
<div class="col-xs-3">
  <%= link_to image_tag(@image.image.thumb('180x180#').url, alt: @image.title, class: 'img-thumbnail'),
              @image.image.url , target: '_blank' %>
  <p><%= @image.image.name%></p>
</div>

<div class="container">
<div class="row">
<aside class="span4">

<fieldset>
<legend>General Informations</legend>
  Dimension:<br>
    <input type="text" value="<%= "#{@exif.width}  x  #{@exif.height}" %>" id="dimension" title="Current dimension of the picture in pixels (width x height">
    <br>
    Original date:<br>
    <input type="text" value="<%= @exif.date_time_original.strftime('%d/%m/%Y - %H:%M') if @exif.date_time_original%>" id="originalDate" title="Original date when the picture was taken">
  <br>
    Model:<br>
    <input type="text" value="<%= @exif.model %>" id="model" title="Brand an Model of the camera">
  <br>
    Last changes:<br>
    <input type="text" value="<%= @exif.date_time.strftime('%d/%m/%Y - %H:%M') if @exif.date_time %>" id="lastChanges" title="Date when the picture was edited on the last time">
    <br><br>
</fieldset>
</aside>
<aside class="span4">
<fieldset>
<legend>Geolocalisation</legend>
  GPS Latitude:<br>
    <input type="text" id="latitude" title="GPS Latitude (horizontal=relative to the equator) where the photo was taken : degree°minute'second"">
    <br>
    GPS Longitude:<br>
    <input type="text" id="longitude" title="GPS Longitude (vertical=relative to the meridian) where the photo was taken : degree°minute'second"">
  <br>
    GPS Altitude:<br>
    <input type="text" id="altitude" title="GPS Altitude where the photo was taken">
  <br>
    Address:<br>
    <input type="text" value="<%= @address.data["formatted_address"] if ! @address.blank? %>" id="address" title="Address where the photo was taken : This information isn't included into EXIF file, it is automatically calculated with GPS coordonates">
  <br><br>
</fieldset>
</aside>
<aside class="span4">
<fieldset>
<legend>Technical Informations</legend>
  Exposition Time (s):<br>
    <input type="text" id="expositionTime" title="Duration of exposure to the light (in second)">
    <br>
    Focal Length (mm):<br>
    <input type="text" value="<%= @exif.focal_length.to_i %>" id="focalLength" title="Focal length of the camera which take the photo (in millimeters)">
  <br>
    ISO Speed Rate:<br>
    <input type="text" value="<%= @exif.iso_speed_ratings %>" id="ISO" title="ISO Speed Rating">
  <br>
    Compression Rate (bits/pixel):<br>
    <input type="text" id="compressionRate" title="Compression rate of the picture (due to format). It represents the number of bits per pixel">
    <br><br>
</fieldset>
</aside>
<div class="col-xs-3">
  <input type="button" class="btn btn-large btn-primary" value = "Download with new exif data"  />
</div
</div>
</div>



<script type="text/javascript">
	var compressedRate = parseFloat(eval("<%= @exif.compressed_bits_per_pixel %>")).toFixed(2);
	var exposure = parseFloat(eval("<%= @exif.exposure_time.to_s %>")).toFixed(2);

	var lat0 = eval("<%= @exif.gps_latitude[0] if @exif.gps_latitude %>");
	var lat1 = eval("<%= @exif.gps_latitude[1] if @exif.gps_latitude %>");
	var lat2 = parseFloat(eval("<%= @exif.gps_latitude[2] if @exif.gps_latitude %>")).toFixed(3);

	var lon0 = eval("<%= @exif.gps_longitude[0] if @exif.gps_longitude %>");
	var lon1 = eval("<%= @exif.gps_longitude[1] if @exif.gps_longitude %>");
	var lon2 = parseFloat(eval("<%= @exif.gps_longitude[2] if @exif.gps_longitude %>")).toFixed(3);

	var alt = parseFloat(eval("<%= @exif.gps_altitude if @exif.gps_altitude %>")).toFixed(1);

	document.getElementById('compressionRate').value = compressedRate;
	document.getElementById('expositionTime').value = exposure;
	document.getElementById('latitude').value = lat0+"°"+lat1+"'"+lat2+"\"";
	document.getElementById('longitude').value = lon0+"°"+lon1+"'"+lon2+"\"";
	document.getElementById('altitude').value = alt;
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
<a target="_blank" href="https://github.com/ggouzi/Rails_Exif_Information">   
<img border="0" alt="https://github.com/ggouzi/Rails_Exif_Information" src="github.ico">We're on Github
</a>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "EXIF EXTRACTION", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "All Images", images_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
	<!-- A decommenter pour les tests --!>
      <!-- <%= debug(params) if Rails.env.development? %> --!>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>Why am I here ?</h1>
<p>
  	This Rails application allow you to see metadatas stored in your pictures and to edit them.

</p>
<p>
	These datas are extracted from EXIF files.
</p>
<p>
	Beyond the funny side, we are trying to inform people about the fact that hidden datas are stored without your knowledge.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  	Open a picture by clicking on the button "Open picture" and select the picture you want to analyse from your computer.
</p>
<p>
	You can also drag the picture from your computer and drop it into the browser.
</p>
<p>
	Fields below will be automaticly filled by metadatas extracted from the picture you choose.
</p>

app/views/static_pages/home.html.erb
  <div id="dropper" class="center hero-unit">
    <h1>Extract data from pictures</h1>
    <h2>Open a picture or drop it here.</h2>

<input type="file" id="src" style="display:none;" onChange="showImage(this);"/>
<img id="target" exif="true"/>
<input type="button" class="btn btn-large btn-primary" value = "Open picture" onclick="getfile();"/>
<input type="button" class="btn btn-large btn-primary" value = "Edit datas" style="display:none" onclick="changeDatas();"/>

<%= simple_form_for (@image, remote: true) do |IMG| %>
  <%= IMG.input :username, type: :file,label_html: { id: 'src' }  %>
  <%= IMG.button :submit, remote: true %>
<% end %>

<script type="text/javascript">
    function getfile(){
        document.getElementById('src').click();
		<% require 'exifr' %>
		<% require 'geocoder' %>
		// Comment récupèrer le chemin de l'image (en js) et la passer en paramètre de la fonction new (en ruby) ?
		/*<% exif = EXIFR::JPEG.new("/Users/robinroyer/Documents/developpement/depot-git/HelloRuby/ruby_extract_exif/test8.jpg")%>
		document.getElementById('dimension').value="<%= exif.height%>"+"x"+"<%= exif.width%>";
		document.getElementById('originalDate').value="<%= exif.date_time_original%>";
		document.getElementById('model').value="<%= exif.make%>"+"-"+"<%= exif.model%>";
		document.getElementById('lastChanges').value="<%= exif.date_time%>";

		document.getElementById('latitude').value="<%= exif.gps_latitude_ref%>"+"-"+"<%= exif.gps_latitude%>";
		document.getElementById('longitude').value="<%= exif.gps_longitude_ref%>"+"-"+"<%= exif.gps_longitude%>";
		document.getElementById('altitude').value="<%= exif.gps_altitude%>";

		document.getElementById('expositionTime').value="<%= exif.exposure_time.to_s%>";
		document.getElementById('focalLength').value="<%= exif.focal_length.to_i%>";
		document.getElementById('ISO').value="<%= exif.iso_speed_ratings%>";
		document.getElementById('compressionRate').value="<%= exif.compressed_bits_per_pixel%>";

		<%=
		query = dps_to_dd(exif.gps_latitude, exif.gps_latitude_ref, exif.gps_longitude, exif.gps_longitude_ref)
		result = Geocoder.search(query).first
		%>
		document.getElementById('address').value="<%=result%>";*/

    }
</script>

<h4><font color="grey">Learn more about
		<a href="https://en.wikipedia.org/wiki/Exchangeable_image_file_format">EXIF files</a>.
    </font>
</h4>
</div>

<div class="row">
<aside class="span4">

<fieldset>
<legend>General Informations</legend>
	Dimension:<br>
  	<input type="text" id="dimension">
  	<br>
  	Original date:<br>
  	<input type="text" id="originalDate">
	<br>
  	Model:<br>
  	<input type="text" id="model">
	<br>
  	Last changes:<br>
  	<input type="text" id="lastChanges">
  	<br><br>
</fieldset>
</aside>
<aside class="span4">
<fieldset>
<legend>Geolocalisation</legend>
	GPS Latitude:<br>
  	<input type="text" id="latitude">
  	<br>
  	GPS Longitude:<br>
  	<input type="text" id="longitude">
	<br>
  	GPS Altitude:<br>
  	<input type="text" id="altitude">
	<br>
  	Address:<br>
  	<input type="text" id="address">
	<br><br>
</fieldset>
</aside>
<aside class="span4">
<fieldset>
<legend>Technical Informations</legend>
	Exposition Time (s):<br>
  	<input type="text" id="expositionTime">
  	<br>
  	Focal Length (mm):<br>
  	<input type="text" id="focalLength">
	<br>
  	ISO Speed Rate:<br>
  	<input type="text" id="ISO">
	<br>
  	Compression Rate:<br>
  	<input type="text" id="compressionRate">
  	<br><br>
</fieldset>
</aside>
</div>


 <script>
function showImage(src,target) {
  var fr=new FileReader();
  fr.onload = function(e) { target.src = this.result; };
  src.addEventListener("change",function() {
    fr.readAsDataURL(src.files[0]);
  });

}

var src = document.getElementById("src");
var target = document.getElementById("target");
showImage(src,target);
  </script>